### ISSUE TITLE
"scripts" dependence does not exist

### ISSUE THREAD

**Issue by Barabaika** [bytedance/dplm#1]
Hello, thank you for sharing the code. 
I m trying to run script ./run/dplm_scaffold_gen.sh, but get the following error:
`from scripts.design_pdb import prepare_data
ModuleNotFoundError: No module named 'scripts.design_pdb'`
Seems that there is no **scripts** folder with **design_pdb** function, or i missed something. Could you please take a look on this.

**Comment by zhengzx-nlp** [comment]
Hi Barabaika,

Thank you for bringing this to our attention! We have fixed this and will update it with the next PR very shortly.

**Comment by wxy-nlp** [comment]
Hi Barabaika,

We have updated the code and fixed this problem. Note that before generation, you should download all the scaffold pdb files from https://github.com/microsoft/evodiff/tree/main/examples/scaffolding-pdbs, and place them in the data-bin/scaffolding-pdbs folder. 

If you encounter any other issues, feel free to let us know!
