### ISSUE TITLE
Repeated AA at beginning and end of protein.

### ISSUE THREAD

**Issue by abcdxs117** [bytedance/dplm#12]
Currently seeing a lot of strange amino acid repetitions, usually at beginning and end of generated protein sequences. Is there a way to reduce the frequency of these types of generations?

**Comment by wxy-nlp** [comment]
Hello @abcdxs117 ,
Sorry for the late reply. 
This phenomenon is normal, as we also find repeat pattern in some sequences of the training dataset (UniRef50), so after training model may generate similar repetitions. 
We develop a rejection sampling method to reduce the repetitions, as the following `self.resample_conditional` method.
https://github.com/bytedance/dplm/blob/5545c6d4166f515b4eb66ada41d0ab3178dfe6ca/src/byprot/models/lm/dplm.py#L275-L279
The `ratio` parameter represents the threshold. If the repeat ratio of the predicted sequence (i.e., x_0) of the current timestep exceeds this threshold, then resample it. The threshold is 0.25 by default, further lowering the threshold may reduce the frequency of recurrences, but too low a threshold can also cause resamples to be too frequent and thus decrease quality.
