### ISSUE TITLE
Question regarding the time taken for training and what type of compute that's been used

### ISSUE THREAD

**Issue by haresh121** [bytedance/dplm#14]
Hi,
Can you please answer the following questions

1. How much time is taken for the DPLM to get trained on the datasets mentioned ?
2. What are the memory requirements and on what type of GPU that you've performed the training on ?

**Comment by wxy-nlp** [comment]
Hi @haresh121,
Sorry for the late reply. The time and memory cost during training is as below:
1) DPLM 150M:
