### ISSUE TITLE
403 Error When Downloading CATH Data in bash scripts/download_cath.sh

### ISSUE THREAD

**Issue by biocuckooHXH** [bytedance/dplm#16]
I followed the instructions in your README.txt to run ByProt's bash scripts/download_cath.sh and successfully obtained the cath4.3 data using the following command: wget -r -nd -np https://dl.fbaipublicfiles.com/fair-esm/data/cath4.3_topologysplit_202206/chain_set.jsonl -P data/cath_4.3
However, I encountered a 403 Forbidden error when attempting to download the split.jsonl file with the command: 
wget -r -nd -np https://dl.fbaipublicfiles.com/fair-esm/data/cath4.3_topologysplit_202206/split.jsonl -P data/cath_4.3
Is there an alternative way to access this file or any updated links that should be used? Please provide guidance on how to resolve this issue. Thank you!

**Comment by wxy-nlp** [comment]
Hi @biocuckooHXH ,
Sorry for the late reply! You can access the cath_4.3 by downloading the `cath_4.3.zip` in this [link](https://drive.google.com/file/d/1lPmyCn1fSP0AI9zoO3OBo39Z1H_Uosb4/view?usp=sharing) and unzip it.
