### ISSUE TITLE
 No module named 'yaml_config_override'

### ISSUE THREAD

**Issue by done520** [bytedance/dplm#6]
representationlearning:
 when run  "python scripts/training.py --config ..." get errors：

```
    from yaml_config_override import add_arguments
ModuleNotFoundError: No module named 'yaml_config_override'

```

**Comment by wxy-nlp** [comment]
Hi done520,

Thanks for pointing this and we have updated the "environment.sh" for installing environment.
You do not need to install all the packages again and can just use
`pip install yaml-config-override==0.5`
 to solve this problem.
